# Generated by Django 4.2.2 on 2023-08-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_products_name'),
        ('barista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.products'),
        ),
    ]
