# Generated by Django 4.2.2 on 2023-07-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
        ('barista', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='work_schedule',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.workschedule'),
        ),
    ]
