# Generated by Django 4.2.2 on 2023-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_products_name'),
        ('barista', '0002_order_supplements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplements',
        ),
        migrations.AddField(
            model_name='order',
            name='supplements',
            field=models.ManyToManyField(blank=True, null=True, to='menu.products'),
        ),
    ]
