# Generated by Django 4.2.2 on 2023-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('barista', '0003_remove_order_work_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_contents',
        ),
        migrations.AddField(
            model_name='order',
            name='order_contents',
            field=models.ManyToManyField(to='menu.menuitem'),
        ),
    ]
