# Generated by Django 4.2.2 on 2023-08-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_products_name'),
        ('barista', '0003_remove_order_supplements_order_supplements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supplements',
            field=models.ManyToManyField(blank=True, to='menu.products'),
        ),
    ]
